server:
  port: 7002
spring:
  application:
    name: cloud-eureka-service7002
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3307/cloud_db_2020?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456

eureka:
  eureka:
    server:
      renewal-percent-threshold: 0.85
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机就是自己
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群指向其它eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    #清理注册服务间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 2000
