server:
  port: 7001
spring:
  application:
    name: cloud-eureka-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3307/cloud_db_2020?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456

eureka:
  eureka:
    server:
      renewal-percent-threshold: 0.85
  instance:
    hostname: loaclhost #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #单机就是自己
      #defaultZone: http://eureka7002.com:7002/eureka/
